version: '3.7'

services:
  php:
    container_name: phonebook_php
    build: ./docker/php/
    volumes:
      - ./:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - postgres
    working_dir: /var/www/app
    networks:
      - internal

  nginx:
    container_name: phonebook_nginx
    image: nginx:alpine
    depends_on:
      - php
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '8086:8086'
    networks:
      - internal

  postgres:
    container_name: phonebook_postgres
    image: postgres:11
    ports:
      - '5434:5432'
    working_dir: /var/www/app
    restart: on-failure
    environment:
      POSTGRES_DB: phonebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/dump:/app/dump
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgresql:

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.127.0/28
